"""initial schema

Revision ID: 2e1fdaf99c5d
Revises: 
Create Date: 2026-08-20 17:14:35.941043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e1fdaf99c5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('nearby_landmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency_contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colleges_city'), 'colleges', ['city'], unique=False)
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=False)
    op.create_table('offers',
    sa.Column('platform', sa.Enum('zomato', 'swiggy', 'amazon', 'flipkart', 'other', name='offer_platform'), nullable=False),
    sa.Column('category', sa.Enum('food', 'shopping', 'student', 'other', name='offer_category'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount', sa.String(length=100), nullable=False),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('student_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_table('local_services',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('mess', 'medical_store', 'atm', 'grocery', name='local_service_category'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('distance_from_college_km', sa.Float(), nullable=True),
    sa.Column('opening_hours', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_services_category'), 'local_services', ['category'], unique=False)
    op.create_index(op.f('ix_local_services_college_id'), 'local_services', ['college_id'], unique=False)
    op.create_index(op.f('ix_local_services_id'), 'local_services', ['id'], unique=False)
    op.create_table('pg_listings',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('accommodation_type', sa.Enum('pg', 'hostel', name='accommodation_type'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('has_mess', sa.Boolean(), nullable=False),
    sa.Column('gender_preference', sa.String(length=20), nullable=True),
    sa.Column('distance_from_college_km', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pg_listings_college_id'), 'pg_listings', ['college_id'], unique=False)
    op.create_index(op.f('ix_pg_listings_id'), 'pg_listings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', name='user_role'), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('source_location', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('railway_station', 'airport', 'bus_stand', 'other', name='source_type'), nullable=False),
    sa.Column('source_latitude', sa.Float(), nullable=True),
    sa.Column('source_longitude', sa.Float(), nullable=True),
    sa.Column('transport_type', sa.Enum('metro', 'bus', 'cab', 'auto', 'walk', 'mixed', name='transport_type'), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('estimated_cost_inr', sa.Float(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('polyline', sa.String(), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_college_id'), 'routes', ['college_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_user_id'), 'routes', ['user_id'], unique=False)
    op.create_table('student_tips',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_tips_college_id'), 'student_tips', ['college_id'], unique=False)
    op.create_index(op.f('ix_student_tips_id'), 'student_tips', ['id'], unique=False)
    op.create_index(op.f('ix_student_tips_user_id'), 'student_tips', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=True),
    sa.Column('pg_listing_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('review_type', sa.Enum('college', 'pg', 'hostel', 'route', name='review_type'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pg_listing_id'], ['pg_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_college_id'), 'reviews', ['college_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_pg_listing_id'), 'reviews', ['pg_listing_id'], unique=False)
    op.create_index(op.f('ix_reviews_route_id'), 'reviews', ['route_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_route_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_pg_listing_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_college_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_student_tips_user_id'), table_name='student_tips')
    op.drop_index(op.f('ix_student_tips_id'), table_name='student_tips')
    op.drop_index(op.f('ix_student_tips_college_id'), table_name='student_tips')
    op.drop_table('student_tips')
    op.drop_index(op.f('ix_routes_user_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_college_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pg_listings_id'), table_name='pg_listings')
    op.drop_index(op.f('ix_pg_listings_college_id'), table_name='pg_listings')
    op.drop_table('pg_listings')
    op.drop_index(op.f('ix_local_services_id'), table_name='local_services')
    op.drop_index(op.f('ix_local_services_college_id'), table_name='local_services')
    op.drop_index(op.f('ix_local_services_category'), table_name='local_services')
    op.drop_table('local_services')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_city'), table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
